config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get 'about', to: 'pages#about', as: :about
  get 'option', to: 'pages#option', as: :option
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def option
    @countries = ["Myanmar", "Cambodia", "Laos", "Indonesia", "Philipines", "Borneo"]

      if params[:country]
        @countries = @countries.select { |country| country.start_with?(params[:country])}
      end
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsIntro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> About us! </h1>
<h2> We are a team of travellers who have spent months travelling Asia</h2>
<p> We have routes around many South East Asian countries for travellers on a budget,
who don't want to spend hours researching routes but still want to see all the good stuff!</p>

app/views/pages/home.html.erb
<%= link_to "Know more about us", about_path %>
<%= link_to "See the countries", option_path %>

app/views/pages/option.html.erb
<h2>See our countries!</h2>
<ul>
  <% @countries.each do |country| %>
    <li> <%= country.capitalize %></li>
  <% end %>
</ul>

<form action="/option" method="get">
<input type="text" name="country" value="<%= params[:country] %>" placeholder="What country are you going to?">
<input type="submit">
</form>